version: '3.8'

services:
  bot:
    build: .
    command: python main.py
    env_file:
      - ./token.env
    depends_on:
      - redis
    restart: always
    dns:
      - 8.8.8.8

  celery:
    build: .
    command: celery -A celery_app.app worker --loglevel=info
    env_file:
      - ./token.env
    depends_on:
      - redis
    restart: always
    dns:
      - 8.8.8.8

  redis:
    image: redis:7
    ports:
      - "6379:6379"